### ISSUE TITLE
Bug: running npm run vercel-build for the first time fails to pre-render /global-stats

### ISSUE THREAD

**Issue by slowSort** [Sage-Future/fatebook#85]
Hey there 👋. 

I'm running through the readme to get setup. The first time I ran vercel-build I got this error

```
TypeError: Cannot read properties of undefined (reading 'values')
    at /Users/danielgibbons/Desktop/Codebases/2024/fatebook/.next/server/pages/global-stats.js:1:253660
    at Array.map (<anonymous>)
    at /Users/danielgibbons/Desktop/Codebases/2024/fatebook/.next/server/pages/global-stats.js:1:250226
    at Array.map (<anonymous>)
    at T (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/.next/server/pages/global-stats.js:1:249735)
    at Wc (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)

Error occurred prerendering page "/global-stats". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: Cannot read properties of undefined (reading 'values')
    at /Users/danielgibbons/Desktop/Codebases/2024/fatebook/.next/server/pages/global-stats.js:1:253660
    at Array.map (<anonymous>)
    at /Users/danielgibbons/Desktop/Codebases/2024/fatebook/.next/server/pages/global-stats.js:1:250226
    at Array.map (<anonymous>)
    at T (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/.next/server/pages/global-stats.js:1:249735)
    at Wc (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/danielgibbons/Desktop/Codebases/2024/fatebook/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)
```

Apologies there's not much more I can give right now - it's not blocking me running the app locally and I don't think I've got the domain knowledge to make a good crack at this at the moment. I plan on trying to tackle a few of the other issues with "help wanted" tags, but I wanted to raise this first before I timed out tonight. 

First issue so let me know if there's anything I can do to raise issues better in future!

All the best,

Daniel

**Comment by adam-binks** [comment]
Hi Daniel, thanks for your interest in contributing!

To run the app locally, you can run `npm run dev`, and it should open in your browser.

Thanks for reporting this issue - I hadn't spotted this as this only happens when your test database is empty. I've pushed a quick fix for it, let me know if you run into any more issues: https://github.com/Sage-Future/fatebook/commit/d03a0c5ced4cf804d4ad32690a9c80cc73b30b9a

**Comment by slowSort** [comment]
Hi Adam, can confirm that it's fixed over here, nice one :)
